project_name: go-pipeline
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- 
  id: gopipeline
  binary: gopipeline
  main: ./cmd/go-pipeline/main.go
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  ldflags:
  - -X main.Build={{ .ShortCommit }}
  - -X main.Major={{ .Major }}
  - -X main.Minor={{ .Minor }}
  - -X main.Patch={{ .Patch }}
  - -X main.Label=release
  goos:
  - windows
  - darwin
  - linux
  ignore:
  - goos: darwin
    goarch: 386

archives:
- 
  id: gopipeline-archive
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
  format_overrides:
  - goos: windows
    format: zip
  files: [a-workaround-to-include-only-the-binary*]
  wrap_in_directory: false

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.sha256"

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  -
    id: gopipeline-nfpms
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    builds:
    - gopipeline
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
    vendor: Jon Friesen
    homepage: https://github.com/jonfriesen/github-actions-pipeline
    maintainer: Jon Friesen <jon@jonfriesen.ca>
    description: GoReleaser + GitHub Actions pipeline for Go CLI projects
    license: MIT
    formats:
    - deb
    - rpm

s3:
  -
    bucket: goreleaser-pipeline
    region: sfo2
    folder: "{{ .ProjectName }}/{{ .Tag }}"
    endpoint: "https://sfo2.digitaloceanspaces.com"
    acl: public-read