project_name: gopipeline
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- 
  id: gopipeline
  binary: gopipeline
  main: ./cmd/go-pipeline/main.go
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  ldflags:
  - -X main.Build={{ .ShortCommit }}
  - -X main.Major={{ .Major }}
  - -X main.Minor={{ .Minor }}
  - -X main.Patch={{ .Patch }}
  - -X main.Label=release
  goos:
  - windows
  - darwin
  - linux
  ignore:
  - goos: darwin
    goarch: 386

archives:
- 
  id: gopipeline-archive
  name_template: "go-pipeline-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip
  files: [a-workaround-to-include-only-the-binary*]
  wrap_in_directory: false

checksum:
  name_template: "go-pipeline-{{ .Version }}-checksums.sha256"

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

s3:
  -
    bucket: goreleaser-pipeline
    ids:
    - gopipeline-archive
    region: sfo2
    folder: "{{ .ProjectName }}/{{ .Tag }}"
    endpoint: "https://sfo2.digitaloceanspaces.com"
    acl: public-read