# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- main: ./cmd/go-pipeline/main.go
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  ldflags:
  - -X main.Build={{ .ShortCommit }}
  - -X main.Major={{ .Major }}
  - -X main.Minor={{ .Minor }}
  - -X main.Patch={{ .Patch }}
  - -X main.Label=release
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# s3 is technically deprecated by "blobs" which i can't get to work...
s3:
-
  bucket: goreleaser-pipeline
  ids:
  - github-actions-pipeline
  region: sfo2
  folder: "{{ .ProjectName }}/{{ .Tag }}"
  endpoint: "http://sfo2.digitaloceanspaces.com"
  acl: public-read